site_name: dcrdocs
theme: null
theme_dir: tpldcrdocs/
site_url: https://docs.decred.org
repo_url: https://github.com/decred/dcrdocs
markdown_extensions:
  - footnotes
  - fontawesome_markdown
  - smarty
  - mdx_math
  - toc:
      permalink: True
  - tables
extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
    - css/style.css
pages:
- Home: 'index.md'
- Loslegen:
  - "Beginner's Guide": 'getting-started/beginner-guide.md'
  - 'Herunterladen und installieren': 'getting-started/install-guide.md'
  - Paymetheus:
    - 'Paymetheus Setup': 'getting-started/user-guides/paymetheus.md'
    - 'Using Paymetheus': 'getting-started/user-guides/using-paymetheus.md'
  - Command-Line:
    - 'OS Differences': 'getting-started/cli-differences.md'
    - 'Startup Basics': 'getting-started/startup-basics.md'
    - 'dcrd Setup': 'getting-started/user-guides/dcrd-setup.md'
    - 'dcrwallet Setup': 'getting-started/user-guides/dcrwallet-setup.md'
    - 'dcrctl Basics': 'getting-started/user-guides/dcrctl-basics.md'
  - 'Web Wallet': 'getting-started/user-guides/web.md'
  - 'Obtaining DCR': 'getting-started/obtaining-dcr.md'
  - 'Using the Block Explorer': 'getting-started/using-the-block-explorer.md'
  - 'Testnet Voting Guide': 'getting-started/user-guides/testnet-voting.md'
  - 'Decred Constitution': 'getting-started/constitution.md'
- Mining:
  - 'Overview': 'mining/overview.md'
  - 'Proof-of-Stake (PoS)': 'mining/proof-of-stake.md'
  - 'Proof-of-Work (PoW)': 'mining/proof-of-work.md'
  - User Guides:
    - gominer:
      - Pool-Mining:
        - 'Windows Guide': 'mining/proof-of-work/pool-mining/gominer/windows.md'
    - cgminer:
      - Pool-Mining:
        - 'Linux Guide': 'mining/proof-of-work/pool-mining/cgminer/linux.md'
        - 'Windows Guide': 'mining/proof-of-work/pool-mining/cgminer/windows.md'
      - Solo-Mining:
        - 'Linux Guide': 'mining/proof-of-work/solo-mining/cgminer/linux.md'
        - 'Windows Guide': 'mining/proof-of-work/solo-mining/cgminer/windows.md'
- FAQ:
  - 'Overview': 'faq/overview.md'
  - 'General': 'faq/general.md'
  - 'Configuration': 'faq/configuration.md'
  - 'Wallets and Seeds': 'faq/wallets-and-seeds.md'
  - 'Web Client': 'faq/web-client.md'
  - 'Blocks': 'faq/blocks.md'
  - Proof-of-stake:
    - 'Solo Mining': 'faq/proof-of-stake/solo-mining.md'
    - 'Buying Tickets and Fees': 'faq/proof-of-stake/buying-tickets-and-fees.md'
    - 'Voting Tickets': 'faq/proof-of-stake/voting-tickets.md'
    - 'Stake Pools': 'faq/proof-of-stake/stake-pools.md'
  - 'Proof-of-Work Mining': 'faq/proof-of-work-mining.md'
  - 'Common Errors and Solutions': 'faq/errors.md'
- Advanced:
  - 'Overview': 'advanced/overview.md'
  - 'Storing Login Details': 'advanced/storing-login-details.md'
  - 'Program Options': 'advanced/program-options.md'
  - 'Block Header Specifications': 'advanced/block-header-specifications.md'
  - 'Transaction Details': 'advanced/transaction-details.md'
  - 'Verifying Binaries': 'advanced/verifying-binaries.md'
  - 'Deleting Your Wallet': 'advanced/deleting-your-wallet.md'
  - 'Advanced dcrctl Usage': 'advanced/dcrctl-usage.md'
  - 'Contributing Guidelines': 'advanced/contributing.md'
- Research:
  - 'Overview': 'research/overview.md'
  - 'Hybrid Design': 'research/hybrid-design.md'
  - 'Decentralized Stake Pooling': 'research/decentralized-stake-pooling.md'
  - 'Elliptic Curve Signature Algorithms': 'research/elliptic-curve-signature-algorithms.md'
  - 'BLAKE-256 Hash Function': 'research/blake-256-hash-function.md'
  - 'Script Extensions': 'research/script-extensions.md'
  - 'Signature Script Isolation and Fraud Proofs': 'research/signature-script-isolation-and-fraud-proofs.md'
  - 'Transaction Extensions': 'research/transaction-extensions.md'
  - 'Schnorr Signatures': 'research/schnorr-signatures.md'
  - 'Miscellaneous Improvements': 'research/miscellaneous-improvements.md'
- About:
  - 'Support Directory': 'support-directory.md'
  - 'Credits': 'about/credits.md'
  - 'License': 'about/license.md'
copyright: If you wish to improve this site, please <a href="https://github.com/decred/dcrdocs/issues/new"><i class="fa fa-github"></i> open an issue</a> or <a href="https://github.com/decred/dcrdocs/compare"><i class="fa fa-github"></i> send a pull request</a>.<br>dcrdocs v0.0.2. Decred Project 2016.
